---
name: "Deploy"
"on":
  create:
    tags:
    - "*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "graalvm"
        java-version: "23"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.9"
    - run: "mvn -s settings.xml spotless:check deploy -DskipTests=true"
