---
name: "Deploy"
"on":
  create:
    tags:
    - "*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v5"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "graalvm"
        java-version: "23"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.9"
    - run: "git fetch --prune --unshallow --tags"
    - run: "sudo apt-get install -y build-essential zlib1g-dev"
    - run: "mvn -s settings.xml spotless:check deploy -DskipTests=true"
    - run: "mvn -s settings.xml -Pnative package"
    - name: "Release"
      uses: "softprops/action-gh-release@v2"
      with:
        generate_release_notes: "true"
        make_latest: "true"
        token: "${{ secrets.GH_TOKEN }}"
        files: "target/mvn-cleaner"
